### PR TITLE
Update user.clj

### PR DESCRIPTION
**Pull request by jeffp42ker**
Missing directory in location

### CODE REVIEW

**Review by jeffp42ker — COMMENTED** [review]
needed in the form as well:
(toto/live-view! "resources/toto/examples/md/test.md")

**Comment by metasoarous** [comment]
Hi @jeffp42ker.

Thanks for submitting this PR. Any reason why you ended up closing it?

Thanks again

**Comment by jeffp42ker** [comment]
Hi, I was really just getting started and there was not much yet to contribute. I intended to submit a short issue comment when github wizardly took me down a pull request path which seemed silly.

I'm still playing with Toto, thanks for creating it.

**Comment by metasoarous** [comment]
Sure thing; Thanks for giving it a whirl!

**Pull request closed without merging**
